---
- name: define distribution value for mysql upstream repository
  set_fact:
    mysql_upstream_dist: "{% if ansible_distribution == 'Fedora' %}fc{% else %}el{% endif %}{{ ansible_distribution_major_version }}"

- name: ensure mysql upstream repository is installed
  package:
    name: "http://dev.mysql.com/get/mysql{{ mysql_upstream_version | replace('.', '') }}-community-release-{{ mysql_upstream_dist }}-9.noarch.rpm"
