---
- include: security/temp_root_password.yml
- include: security/root_auth_plugin.yml

- name: get remote hosts of root user
  command: mysql -NBe "SELECT Host FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
  register: mysql_remote_root_hosts
  changed_when: false
  check_mode: no

- name: ensure remote root users are removed
  mysql_user:
     name: root
     host: "{{ item }}"
     state: absent
  with_items: "{{ mysql_remote_root_hosts.stdout_lines }}"

- name: get hosts of root users
  command: mysql -NBe "SELECT Host FROM mysql.user WHERE User = 'root' ORDER BY (Host='localhost') ASC"
  register: mysql_root_hosts
  changed_when: false
  check_mode: no

- name: ensure root user has password set
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: "{{ item }}"
  with_items: "{{ mysql_root_hosts.stdout_lines }}"
  when: "mysql_root_password|default('')"

- include: security/my_cnf.yml

- command: mysql -NBe "SELECT Host FROM mysql.user WHERE User = ''"
  register: mysql_anonymous_hosts
  changed_when: false
  check_mode: no

- name: ensure anonymous users are removed
  mysql_user:
     name: ""
     host: "{{ item }}"
     state: absent
  with_items: "{{ mysql_anonymous_hosts.stdout_lines }}"

- name: ensure test database is removed
  mysql_db:
    name: test
    state: absent
